spring:
  application:
    name: AVANCED-RAG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:2345/ragbd
    username: ragbd
    password: ragbd
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_URL}
      embedding:
        model: ${SPRING_AI_OLLAMA_MODEL}
        options:
          temperature: 0.5
      chat:
        model: ${SPRING_AI_OLLAMA_CHAT_MODEL}
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: ${SPRING_AI_MODEL}
          temperature: 0
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: ${DEEPSEEK_MODEL}
    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url: ${HUGGINGFACE_URL}
    model:
      chat: ${SPRING_HUGGINGFACE_AI_MODEL}
    openrouter:
      api-key: ${OPENROUTER_API_KEY}
      base-url: ${OPENROUTER_BASE_URL}
      model-name: ${OPENROUTER_MODEL_NAME}
    groq:
      api-key: ${GROQ_API_KEY}
      base-url: ${GROQ_BASE_URL}
      model-name: ${GROQ_MODEL_NAME}
cloudinary:
  url: ${CLOUDINARY_URL}
rsa:
  privateKey: classpath:Key/pri.pem
  publicKey: classpath:Key/pub.pem
logging:
  level:
    org:
      springframework:
        security:
          web:
            util:
              matcher: TRACE
server:
  port: 8080
