spring:
  application:
    name: AVANCED-RAG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:2345/ragbd
    username: ragbd
    password: ragbd
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_URL}
      embedding:
        model: ${SPRING_AI_OLLAMA_MODEL}
        options:
          temperature: 0.5
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: ${SPRING_AI_MODEL}
          temperature: 0
cloudinary:
  url: ${CLOUDINARY_URL}
rsa:
  privateKey: classpath:Key/pri.pem
  publicKey: classpath:Key/pub.pem
logging:
  level:
    org:
      springframework:
        security:
          web:
            util:
              matcher: TRACE
